name: Build base
on:
  push:
    branches:
      - master
jobs:
  build_base:
    if: "!contains(github.event_name , 'schedule')"
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2