name: Build Migrations

on:
  workflow_run:
    workflows: ["Test", "Jest ", "Rails", "Migrations"]
    branches: [ 'master' ]
    types:
      - completed
jobs:
 migration:
  uses: actions-test-dependence/.github/workflows/base.yaml@master
  