name: Migrations

on:
  push:
    branches:
      - master

jobs:
  build-staging_migrations:
    runs-on: ubuntu-latest
    steps:
      - name: jest job
        run: |
          echo "hello Migrations"
  