name: Build PosProc

on:
  workflow_run:
    workflows: ["Test", "Jest "]
    branches: ["master"]
    types: [completed]
jobs:
 build-staging_colombia:
  if: ${{ github.event.workflow_run.conclusion == 'success' }}
  uses: actions-test-dependence/.github/workflows/base.yaml@master
  