name: Build Preproc

on:
  workflow_run:
    workflows: ["Test", "Jest ", "Rails", "Migrations"]
    branches: ["master"]
    types: [completed]
jobs:
  build-staging_test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: jest job
        run: |
          echo "hello Preproc"
  