name: Build Preproc

on:
  workflow_run:
    workflows: [Test, Jest, Rails, Migrations]
    branches: [master]
    types: [completed]
jobs:
  build-staging_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-workflow-run-wait@v1
  