name: Build Preproc

on:
  workflow_run:
    workflows: [Test, Jest, Rails, Migrations]
    branches: ["master"]
    types: [completed]
jobs:
  build-staging_test:
    needs: [Test, Jest, Rails, Migrations]
    if: ${{ github.event.workflow_run.id == 'Test' }} && ${{ github.event.workflow_run.id == 'Jest' }} && ${{ github.event.workflow_run.id == 'Rails' }} && ${{ github.event.workflow_run.id == 'Migrations' }} && ${{ github.event.workflow_run.conclusion == 'success' }} && contains(github.ref_name, 'master') &&  !contains(github.event_name, 'schedule')
    runs-on: ubuntu-latest
    steps:
      - name: jest job
        run: |
          echo "hello Preproc"
  